name: CI-Build-Kivy

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # Using a verified stable tag
        uses: kivy/buildozer-action@v1.2.2
        with:
          workdir: .
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: medical-app-apk
          path: bin/*.apk
