name: CI-Build-Direct

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-gstreamer-lite-dev libgstreamer1.0-plugins-base-dev
          pip3 install --user --upgrade buildozer Cython==0.29.33 virtualenv

      - name: Build APK with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # قبول الشروط تلقائياً وتشغيل البناء
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: medical-app-apk
          path: bin/*.apk
